/* tslint:disable */
/* eslint-disable */
/**
 * Find and Play
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EventCertain
 */
export interface EventCertain {
    /**
     * 
     * @type {number}
     * @memberof EventCertain
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof EventCertain
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof EventCertain
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof EventCertain
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof EventCertain
     */
    date?: string;
    /**
     * 
     * @type {string}
     * @memberof EventCertain
     */
    sport?: string;
    /**
     * 
     * @type {string}
     * @memberof EventCertain
     */
    organizer?: string;
    /**
     * 
     * @type {number}
     * @memberof EventCertain
     */
    price?: number;
    /**
     * 
     * @type {number}
     * @memberof EventCertain
     */
    seats?: number;
}

export function EventCertainFromJSON(json: any): EventCertain {
    return EventCertainFromJSONTyped(json, false);
}

export function EventCertainFromJSONTyped(json: any, ignoreDiscriminator: boolean): EventCertain {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'date': !exists(json, 'date') ? undefined : json['date'],
        'sport': !exists(json, 'sport') ? undefined : json['sport'],
        'organizer': !exists(json, 'organizer') ? undefined : json['organizer'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'seats': !exists(json, 'seats') ? undefined : json['seats'],
    };
}

export function EventCertainToJSON(value?: EventCertain | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'image': value.image,
        'name': value.name,
        'address': value.address,
        'date': value.date,
        'sport': value.sport,
        'organizer': value.organizer,
        'price': value.price,
        'seats': value.seats,
    };
}


