/* tslint:disable */
/* eslint-disable */
/**
 * Find and Play
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface museum
 */
export interface museum {
    /**
     * 
     * @type {number}
     * @memberof museum
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof museum
     */
    image?: string;
    /**
     * 
     * @type {string}
     * @memberof museum
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof museum
     */
    address?: string;
    /**
     * 
     * @type {string}
     * @memberof museum
     */
    sport?: string;
}

export function museumFromJSON(json: any): museum {
    return museumFromJSONTyped(json, false);
}

export function museumFromJSONTyped(json: any, ignoreDiscriminator: boolean): museum {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'image': !exists(json, 'image') ? undefined : json['image'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'address': !exists(json, 'address') ? undefined : json['address'],
        'sport': !exists(json, 'sport') ? undefined : json['sport'],
    };
}

export function museumToJSON(value?: museum | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'image': value.image,
        'name': value.name,
        'address': value.address,
        'sport': value.sport,
    };
}


